amplitude/Amplitude-JavaScript

src/amplitude.js
I've added some simple code to detect if the user is at the beginning of a new session. This allows me, as a web developer, to use the "amplitude.isNewSession()" function to trigger certain tracking behavior only at the beginning of a session.
The use case I'm solving here is capturing utm_* parameters only once (avoiding a back-button problem), tracking referrers, and generally attaching anything we need to in a "Started Session" event -- a key building-block for web application event tracking.
=> Added support for detecting new sessions

amplitude-snippet.min.js, src/amplitude-snippet.js, test/browser/amplitudejs.html, test/browser/amplitudejs2.html
check that the `window.amplitude` object has `runQueuedFunctions` before trying to run it, otherwise print an error message to console
=> check sdk loaded properly before running queued functions

CHANGELOG.md
Should also be done in the `Releases`
=> Link correctly to the v3.0 breaking changes note

src/amplitude-client.js, src/options.js, test/amplitude-client.js
Adding a config option `trackingOptions` that lets people specify any fields they do not want the SDK to track automatically. These fields include things like platform, language, os_version, ip_address, city, etc. Some of those fields aren't actually tracked by the JS SDK (like ip_address, city, etc) but rather on server-side. So we add the config values to the `api_properties` field, and that can be parsed / handled server-side.
=> Add tracking config

src/amplitude-client.js, src/options.js
The current amplitude URL building code enforces that the endpoint ends with a `/`. That prevents users from using some deeper endpoint. This PR moves the last slash to the config so the user can have any ending on it.
=> Move final url slash to config so endpoints may end without a slash

src/utils.js, test/amplitude-client.js, test/amplitude.js, test/utils.js
* Stop warning when null property values are instrumented
* Allow for objects nested within arrays
=> Property validation

.gitignore, Makefile, package.json, rollup.esm.js, yarn.lock
This adds a new build output file, `amplitude.esm.js`, which is an [ES Module version](https://rollupjs.org/guide/en#output-format) of `amplitude-js`. It's made for users who are using amplitude-js with their own bundler (webpack, rollup, etc). It carries significant bundle size savings (the ES module build is 53% the size of the nocompat build):
| File                  | Bytes  |
|-----------------------|--------|
| amplitude.js          | 188568 |
| amplitude.esm.js      | 89767  |
| amplitude.nocompat.js | 169096 |
=> Add ES Module build: closes #182

CHANGELOG.md, README.md, package.json, src/amplitude-client.js, src/amplitude-snippet.js
Currently, when saving events to AsyncStorage, we we are only using unsentKey as the identifier.
This can cause events from multiple projects to get mixed up. By appending this._storageSuffix,
we are adding more specificity to keep unsent events within the correct project scope.
Addresses: https://github.com/amplitude/Amplitude-JavaScript/issues/203
FYI: no need to do this for web because it is calling `_setInStorage()` which utilizes `this._storageSuffix` already
=> Append this._storageSuffix (which includes API key) to unsentKey

CHANGELOG.md, README.md, package.json, src/amplitude-client.js, src/amplitude-snippet.js, test/amplitude-client.js
This is especially useful when you don't want to track any analytics or drop any analytic cookies prior to asking the users to opt in to analytics.
I've added a configuration (`deferInitialization`) and an API (`enableTracking`) to manage this.
If deferInitialization is set to true AND a customer has yet to opt in, we will locally store their pending logs until they either navigate away or opt in.
Note: This is a little gross because I'm checking whether or not to defer calling the function in EVERY public function. I considered using js decorators but it would require refactoring this to use classes. I considered iterating over an array of public methods and wrapping them, but that makes debugging much more difficult in the future. Ultimately, I opted for readability.
=> Add feature to deferInitialization

src/amplitude-client.js, src/base-cookie.js, src/cookie.js, src/options.js, test/amplitude-client.js, test/base-cookie.js, test/mock-cookie.js, test/tests.js
Introduce a `sameSiteCookie` option. It's set to `None` by default.
The previous unreleased patch to set to `Lax` all the time doesn't seem to be a valid option.
=> Add a same site cookie option

Makefile, bower.json, package.json, rollup.umd.js, src/amplitude-snippet.js
Use an iife module for the amplitude snippet. The UMD module has trouble when loaded on sites using require js.
We'll provide a separate UMD file for folks wishing to load the SDK as a require js module.
=> Use iife for snippet

src/amplitude-client.js, src/constants.js, src/cookie.js, src/metadataStorage.js, src/options.js, test/amplitude-client.js, test/amplitude.js, test/browser/index.html, test/mock-cookie.js
Cookies had this fancy abstraction to mimic local storage. This led to
excessively large cookies.
Rather than storing a large JSON serialized version of the cookie data
we'll now use positional values.
Base64 encoding also led to considerable cookie bloat. Instead we only
Base64 encode the user id field and assume other fields in the cookie
are safe.
You can also forgo using cookie storage altogether with the
disableCookie option. This prevents tracking users across different
subdomains of your site.
=> More compact cookie storage with the option to use local storage

src/language.js, src/options.js, test/language.js
When `window.navigator` is undefined at bootstrap (i.e. react native), the default `language` option will be `undefined`. When then trying to override that at init, the type check in [`parseConfig`]( https://github.com/amplitude/Amplitude-JavaScript/blob/master/src/amplitude-client.js#L309 ) will check the type against `"undefined"` instead of `"string"`. Because of that it's impossible to set the user/device language.
I did not want to change the way the option type checking works, so I changed the default fallback of `getLanguage()` to empty string.
I also took the time to improve unit testing of the `getLanguage()` function.
Open for other ways of solving this! Thank you :)
=> Fix language option type bug

src/amplitude-client.js, src/index.js, test/amplitude-client.js
This should make the callback passed to `onInit` actually useful.
The problem is the global window.amplitude is not assigned by the time amplitude invokes the onInit callbacks. I think in older versions of the SDK, it would just blindly assign itself to window.amplitude when it started up. This was a bit presumptuous as there are a lot of different ways of loading amplitude and the module loader ought to determine that.
Another alternative would be to have onInit calls happen in another tick. This is really hard to do well in a browser. Something like `setTimeout(() => onInit(), 0)` feels ugly and can sometimes take hundreds and hundreds of milliseconds to be called.
The solution here is to simply pass the amplitude instance that has been initialized as a parameter to the `onInit` …
=> Pass the amplitude instance to onInit

src/amplitude-client.js, test/amplitude-client.js, test/amplitude.js
The SDK would invoke the logEvent callback when an event was queued. This behavior is really confusing and looks like an error state to most people. Especially since it used status code 0. This confusing behavior makes people think their instrumentation is failing and sometimes it causes them to needlessly build event queues of their own just to send data to amplitude. 
With these changes, the callback is only invoked when an event is successfully sent or when the SDK gives up and decides it will never send an event.
The `_unsentEvent` and `_unsentIdentify` queues will now contain events with their callbacks `[{ event, callback }]`. Though when we serialize them to localStorage, we only serialize the events.
=> Invoke logEvent callbacks for each event when events are actually sent

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md
- Update Environment section to include React Native cases
- Change Feature_request.md to use correct label
=> Update issue template labels

src/base-cookie.js, src/metadata-storage.js, test/amplitude-client.js
A potential fix for #271: When options (samesite, domain, etc.) are passed into the sdk, pass them into `areCookiesEnabled` on initializing `MetadataStorage`.
Fixes a test that was passing in the wrong option for metadata storage
=> fix(cookies): respect the options passed into cookies when testing to see if they're enabled

src/amplitude-client.js, src/constants.js, src/options.js, test/amplitude-client.js, test/browser/amplitudejs.html
This is related to a recent Growth Eng effort to audit and optimize our UTM tracking and attribution.  We would like a way to log an Amplitude event whenever attribution data is captured (utm, referrer, gclid).  This is to compare our Amplitude SDK attribution with our alternative UTMz tracking setup on the corpsite & blog (already added a similar event here: https://github.com/amplitude/amplitude.com/pull/133).
We want to be able to get a full picture of **every** UTM/attribution state that a user has had during their Journey with Amplitude.  Because Identify calls are not queryable, we are unable to devise a query that returns the information we are looking for.  Also, because attribution consists of many properties (utm_source, utm_medium, utm_campaign, etc.), not all of them will have …
=> feat: add logAttributionCapturedEvent option

.github/workflows/release.yml, .github/workflows/test.yml, release.config.js, scripts/deploy_s3.py
Fixes `deploy_s3.js` bug and documentation nits from #297
=> ci: docs and file name fix

src/amplitude-client.js
This PR adds `this` as the argument for `onInit` every time it is called (or really, adding it to a single place where it wasn't being sent)  - this guarantees that the user always has a safe and full Amplitude object when `onInit` is called.
=> fix(initialization): always return `this` in onInit

package.json, website/README.md
=> fix: move bad postinstall script

src/amplitude-client.js, test/amplitude-client.js
Fixes #302 
Please let me know, if there are any problems.
=> fix: Fall back to the other ways, if the device Id is not available from get queries #302

src/amplitude-client.js
- Make `AmplitudeClient.onInit` public. It's [stubbed in the snippet](https://github.com/amplitude/Amplitude-JavaScript/blob/master/src/amplitude-snippet.js#L36), isn't used privately anywhere, and seems like it would be valuable for users who load through snippets.
* Does your PR have a breaking change?:  NO
=> feat: make oninit public

.github/workflows/release.yml
Changes the semantic-release bot author from the default [semantic-release-bot](https://github.com/semantic-release-bot) to our own [amplitude-sdk bot](https://github.com/amplitude-sdk-bot). Example: 
* Does your PR have a breaking change?:  NO
=> ci: change ci bot author

src/options.js, test/amplitude-client.js, test/amplitude.js, test/cookie.js
Resolves issue #275 - reduce the cookie expiration to only 1 year to be GDPR compliant by default. 
=> fix(cookies): reduce cookie lifetime

package.json, src/amplitude-client.js, yarn.lock
- Fixes browser edge case where Prototype.js injects Array.prototype.toJSON and breaks the built-in JSON.stringify()
- @TODO: Tested with local symlinks, but need to publish Amplitude-Node to use new utils
- Related PR: https://github.com/amplitude/Amplitude-Node/pull/45
=> fix: Prototype js fix

CHANGELOG.md, package.json, release.config.js, yarn.lock
- Remove `yarn semantic release` (semantic-release should be called through `npx` rather than yarn)
- Add `@semantic-release/changelog` step that will update `CHANGELOG.md` (didn't know about it during the initial release pipeline PR)
- Manually updated changelog for past releases 
* Does your PR have a breaking change?:  NO
=> build: semantic release changelog

src/utils.js, test/utils.js
Fixes #311 by using syntax that is allowed for null objects created by `Object.create(null)` (map-likes)
Should we be using it when creating jsons? Maybe.
=> fix(validation): Be able to take in and validate null object event/user properties

src/amplitude-client.js, src/constants.js, src/metadata-storage.js, src/options.js, test/amplitude-client.js
As discussed in #317, this PR creates a new option `storage` to be able to use `sessionStorage` for persisting the amplitude IDs with the session storage or even `none`to not persist anything. These are options are useful for privacy as callers of the Amplitude lib can now limit the persistant footprints on users' browsers.
* Does your PR have a breaking change?: no
=> feat(privacy): Add a `storage` option

src/amplitude-client.js, test/amplitude-client.js
- Failed events (e.g. offline user or content blocker) are stored in local storage to be resent at a later time
- When the number of saved events in local storage exceeds [`maxSavedCount`](https://github.com/amplitude/Amplitude-JavaScript/blob/fix-logevent-callback-on-fail/src/options.js#L42), the oldest events will be dropped but the associated callback won't be called. This PR fixes this
- Fixes #142
- Closes #329 
=> fix: Bug with logEvent callbacks not being called when unsent events are dropped 

.eslintrc.json, package.json, src/amplitude-client.js, src/amplitude-snippet.js, src/amplitude.js, src/identify.js, src/index.js, src/utils.js, test/browser/.eslintrc.json, yarn.lock
We are heavy users of the Object prototype `hasOwnProperty`. In general, these should not be called directly - especially on user-created inputs. Allows a lint override to be removed.
Did not add it to the `tests/browsers` dir because I'm not linting sinon or chai 🤷 
=> fix(lint): Do not directly call object builtins 

.github/pull_request_template.md, .github/workflows/semantic-pr.yml, release.config.js, website/README.md
Support for changing primary branch
=> build: switch primary branch to main

src/amplitude-client.js, test/amplitude-client.js
Use SDK consumer-supplied `onError` function throughout the codebase and make sure it is properly invoked if an error occurs during initialization
=> fix: call onError in init function

src/amplitude-client.js
Not a bug, but would be confusing down the line. `sendEventsIfReady` takes no args.
=> fix: remove argument to function that takes no arguments

src/amplitude-client.js, src/options.js, src/xhr.js, test/amplitude-client.js
- Adds `headers` to `options`
- Extract hardcoded headers to `options.headers`
- Adds tests for default and custom headers
- Closes #365 
=> feat: Add HTTP header configurations to options

src/base-cookie.js, test/base-cookie.js
- Add `finally` codeblock to handle cleanup of `amp_cookie_test`.  Will stop excess cookies in header requests.
- Fixes #326
=> fix:  Cleanup test cookies

src/base-cookie.js, src/constants.js, src/metadata-storage.js, test/base-cookie.js
When loading data from cookies, check for duplicate cookies with the same name and dedup to a single cookie with the most recent event time
=> fix(cookies): AMP-35904 dedup cookies

src/amplitude-client.js, src/base-cookie.js, src/metadata-storage.js, test/amplitude-client.js
Adds an API to AmplitudeClient `clearStorage` that wipes user metadata. Escape hatch to help weird edge cases where user's datastorage is malformed somehow.
=> feat: Clear Storage API

src/amplitude-client.js, src/utils.js, test/amplitude-client.js
Periods in device ID checks broke the SDK storage behavior. This is because metadata is stored in cookies and delimited by periods. This PR fixes the behavior by rejecting device IDs with periods
=> fix: Prevent periods in device id check

src/amplitude-client.js, test/amplitude-client.js
Adds an error callback to the various event logging methods
The tricky part to this is that the existing callback has very specific behavior _not_ to be called when there's an error, except in the case where the error is with the state of the sdk client. In order to not break that behavior, I did the following
- call both the existing callback and the new error callback wherever just the old callback was previously called for errors (not instantiating the API key, etc)
- Calling just the error callback when a log request returns with something besides a 200
* Does your PR have a breaking change?:  
https://amplitude.atlassian.net/browse/AMP-35348
=> feat: Add error callback

src/metadata-storage.js
Ensures MetadataStorage.clear() returns false if no metadata existed
https://amplitude.atlassian.net/browse/AMP-38456
=> fix: LGTM return fix for falsy str

package.json, src/amplitude-client.js, test/ua-parser.js, yarn.lock
Populate device model from mobile browser
UAParser library to be updated
=> feat: Mobile device model support

src/options.js
=> feat: add cross origin resource policy header

src/amplitude-client.js, src/options.js, test/amplitude-client.js
add observe plan in options 
allow to pass in event
=> feat: add observe plan options

src/index.js, src/language.js, src/localstorage.js
We have a number of NextJS applications using amplitude, but we currently need to do something like the following to be able to use the library:
```js
useEffect(() => {
import('amplitude-js').then((amplitude) => {
amplitude.getInstance().init(API_KEY);
amplitude.getInstance().logEvent('foo');
});
}, []);
```
If instead we were to have a static
```
import amplitude from 'amplitude-js'
```
at the top of our modules, we'd see errors due to amplitude trying to access global browser variables such as `window` and `navigator` when trying to load the module.
While I understand that this library is intended for use in the browser and there's a separate package for use in Node environments, our use case is to simply be able to `import` the module rather than having to use a dynamic import. We …
=> fix: allow amplitude to be imported/required during SSR

package.json
I noticed the build produces an `amplitude.esm.js` file, but is not referenced in the `package.json`. This PR adds the `module` entry point to the `package.json` so folks using ESM along with bundlers like webpack, parcel, etc will automatically use the ESM version of amplitude rather than the UMD/CJS version.
=> feat: add esm entry point

src/amplitude-snippet.js
Adds `setLibrary` to the list of stubbed snippet proxy methods (related to #443)
=> fix: Add missing setLibrary API to snippet distribution

src/amplitude-snippet.js
Adds missing setTransport API to snippet
=> fix: Add missing setTransport API to snippet

src/amplitude-client.js, src/amplitude-snippet.js, test/amplitude-client.js
Expose more interfaces for flutter web support
The following are the API added in this pr. 
1. getDeviceId
2. getUserId
3. setMinTimeBetweenSessionsMillis
4. setEventUploadThreshold
5. setUseDynamicConfig
6. setServerZone
7. setServerUrl 
=> feat: add more interface for flutter web support

src/amplitude-client.js, src/amplitude-snippet.js, test/amplitude-client.js
1. update setLibrary 
2. add outOfsession parameter in identify api
3. add  groupIdentify and identify out of session test
=> feat: update setLibrary api make it ignore the null value of name or version 

src/amplitude-client.js, src/options.js, test/amplitude-client.js
This PR adds support for on new session start callback. Callback functions can be registered to `onNewSessionStart` event using the following ways:
```javascript
amplitude.getInstance().onNewSessionStart(() => {
console.log('new session - method 1');
});
```
```javascript
amplitude.init('API_KEY', USER_ID, {
onNewSessionStart: () => {
console.log('new session - method 2')
},
});
```
* Unit tests are passing
* Manually tested by executing the following below:
```
// cookies are deleted and page is refreshed
// register onInit callback
> amplitude.getInstance().onInit(() => console.log('init'))
// register session callback 1
> amplitude.getInstance().onNewSessionStart(() => console.log('session - method 1'))
// register session callback 2
// invoke init - runs registered callback fns
> …
```
=> feat: add support for on new session start callback

package.json, yarn.lock
The change bumps dependency to @amplitude/ua-parser-js@0.7.26. Upgrading to this version fixes https://github.com/amplitude/Amplitude-JavaScript/issues/435.
* Unit tests are passing
* Does your PR have a breaking change? None
=> fix: upgrade to @amplitude/ua-parser-js@0.7.26

src/amplitude-snippet.js
PR https://github.com/amplitude/Amplitude-JavaScript/pull/455 adds a new public method. This public method needs to be added to the snippet to allow the method to be called while amplitude.js script is being loaded.
* Does your PR have a breaking change? None
=> fix: add public method onNewSessionStart to snippet

README.md
`README.md` contains links pointing to `master` branch. The said branch is no longer maintained and contains outdated information. With `README.md` being the one of the first docs developers will go through, it is important that it contains up-to-date information about this repository.
* Does your PR have a breaking change? No
=> docs: replace links pointing to master with links pointing to main

Makefile
This change includes a fix to the build step that generates `amplitude-segment-snippet.min.js`.
Currently, the build steps fails on minify, after `grep` pipes code to minify that contains syntax errors. The syntax error stems from to an incorrect pattern used in `grep`. The pattern was previously working with unstyled code until prettier was introduced in this [commit](https://github.com/amplitude/Amplitude-JavaScript/commit/79585d5b84d814932783c97bae851ac361b548a5#diff-8225cfb965ecb3a71b11e26c0fde0e40e7d74db041de68803130320053d891edR17-R21).
After prettier was introduced, the following line in `src/amplitude-snippet.js`:
```js
as.onload = function() {if(!window.amplitude.runQueuedFunctions) {console.log('[Amplitude] Error: could not load SDK');}};
```
turned into:
```js
as.onload = …
```
=> build: fix build for amplitude-segment-snippet.min.js

package.json
In the past, a [change](https://github.com/amplitude/Amplitude-JavaScript/commit/313533ded6bb69a963a6a45424efae3f424641f1) was introduced that moved [@babel/runtime](https://babeljs.io/docs/en/babel-runtime) as dev dependency. The said change was included in [v5.3.1](https://www.npmjs.com/package/amplitude-js/v/5.3.1) and is in effect until latest [v8.13.0](https://www.npmjs.com/package/amplitude-js/v/8.13.0).
As mentioned in @babel/runtime [docs](https://babeljs.io/docs/en/babel-runtime#usage):
> This is meant to be used as a runtime dependency along with the Babel plugin @babel/plugin-transform-runtime. Please check out the documentation in that package for usage.
This PR fixes https://github.com/amplitude/Amplitude-JavaScript/issues/451
Using …
=> fix: make @babel/runtime production dependencies

Makefile, package.json, yarn.lock
This PR drops dependency on uglify@2 and solely utilizes uglify@3. uglify@2 is previously used to minify snippet files. uglify@3 is previously only used to minify source files through [rollup-plugin-uglify](https://www.npmjs.com/package/rollup-plugin-uglify). This allows this package to depend on a single version of uglify for ease of development.
Specifically, `package.json` is updated to use `uglify@^3.4.9` to match the the [version this package indirectly depends on](https://github.com/amplitude/Amplitude-JavaScript/blob/main/yarn.lock#L6983-L6991). Although, the version ultimately resolves to [uglify@3.10.2](https://github.com/amplitude/Amplitude-JavaScript/blob/main/yarn.lock#L8153-L8156).
More details was discussed and documented internally.
* Does your PR have a breaking change? No
=> build: use uglify@3 to minify snippet files and drop uglify@2

src/amplitude-client.js
- added runNewSessionStartCallback method call on new sessionId detect on logEvent time
* [*] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-JavaScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
=> feat: add runNewSessionStartCallback on new sessionId on log event

Makefile
The generated snippet files published to GitHub packages are using the prior release version. Though GitHub packages isn't a main distribution channel for Amplitude, accuracy of build files are very important. This PR fixes the build process to update versions first in targeted files before generating the snippet files.
=> build: fix amplitude sdk version in amplitude-snippet.min.js output

Makefile, karma-web-worker.conf.js, package.json, src/amplitude-client.js, src/base-cookie.js, src/base64.js, src/config-manager.js, src/cookiestorage.js, src/get-host.js, src/get-location.js, src/global-scope.js, src/index.js, src/localstorage.js, src/metadata-storage.js, src/top-domain.js, src/utils.js, src/worker-storage.js, src/xhr.js, test/global-scope.js, test/tests.js, test/utils.js, test/web-worker.js, test/worker-storage.js, yarn.lock
https://amplitude.atlassian.net/wiki/spaces/GOV/pages/1708655504/JS-SDK+Web+Worker+Support+for+amplitude-js
This PR add support to JS SDK usage in web worker.
```html
<html>
<head></head>
<body>
<button id="btn-main">click me</button>
</body>
<script src="amplitude.js"></script>
<script src="app.js"></script>
</html>
```
**app.js**
```js
amplitude.getInstance().init(API_KEY, USER_ID);
const worker = new Worker('worker.js');
document.getElementById('btn-main').addEventListener('click', () => {
amplitude.getInstance().logEvent('btn-main:click');
worker.postMessage({
trigger: 'btn-main:click',
ampl: {
userId: amplitude.getInstance().getUserId(),
deviceId: amplitude.getInstance().getDeviceId(),
sessionId: amplitude.getInstance().getSessionId(),
},
});
});
```
**worker.js**
```js …
```
=> feat: support web worker env

src/worker-storage.js, test/worker-storage.js
This PR is to reset worker storage length when calling `clear()` function.
=> fix: Add missing worker storage length for clear method

release.config.js
Re-orders release.config.js steps so that `create-snippet-instructions.js` will run before NPM publishes
=> build: Make snippet instructions available to public

src/amplitude-client.js, src/options.js, src/utils.js, test/amplitude-client.js, test/utils.js
This change allows custom session id to be defined on init() by passing in config object.
```js
amplitude.init(API_KEY, USER_ID, {
sessionId: Date.now(),
});
```
`config.sessionId` is optional and defaults to `null`. If `options.sessionId` is `null` or not a valid session id, the session id will be set to the session id from metadata storage if it exists; otherwise will be assigned a new one. If `options.sessionId`, it will be set as the session id.
Prior to this change, devs must call `init()` then `setSessionId()` to pass a custom session id.
=> feat: accept custom session id parameter in config

src/xhr.js, test/amplitude-client.js
A change was introduce in v8.7.0 that enforces cors in request headers by default. There isn't a way to remove it for users who do not need it. This change allows cors to be removed from request headers by passing `''`, `null`, `undefined` to `config.headers['Cross-Origin-Resource-Policy']` on init.
```js
amplitude.getInstance().init(<API_KEY>, <USER_ID>, {
headers: {
'Cross-Origin-Resource-Policy': undefined,
}
});
```
=> feat: allow cors header to be excluded from request headers

src/amplitude-client.js, test/amplitude-client.js
Catch top-level errors on Request.send in logEvents(). 
If send fails (XHR is unavialable) then events are removed from the queue after logging errors.
=> fix: catch errors with Request.send

src/amplitude-client.js, src/amplitude.js
Fixes jsdoc for `setGroup()` and `logEventWithGroups()` to replace old url to new url
Old link: https://developers.amplitude.com/docs/setting-user-groups
New link: https://developers.amplitude.com/docs/javascript#user-groups
=> docs: fix link to user group docs

src/base-cookie.js
Fixes https://github.com/amplitude/Amplitude-JavaScript/issues/481
`areCookiesEnabled()` creates a cookie that gets rejected by firewalls due to some special characters included in TZ names. It should be safe to replace this cookie value with virtually anything (w/o special characters) since this is short lived and only used to determine if cookies are enabled. I decided to change it to a random-ish value, to avoid potential conflict.
=> fix: use uuid for test cookie value

src/amplitude-client.js, src/options.js, test/amplitude-client.js
Add versionId to tracking plan data
=> feat: Add versionId to tracking plan data

.github/workflows/release.yml
Remove the need for IAM user creds to publish snippet build artifacts to AWS S3. Switches to using IAM role.
=> build: fix s3 deployment to use iam role

src/amplitude-client.js
Because this domain value is needed while initializing metadata storage, assign `options.domain` after cookie storage options are given. 
=> fix: assign domain after cookie storage options are given

src/utils.js
IE does not support `String.prototype.includes` therefore replacing with `String.prototype.indexOf`
=> fix: replace String.prototype.includes with String.prototype.indexOf

.github/workflows/release.yml
Fix perms for github token used in release workflow. This allows github token to read tokens needed to communicate with aws.
=> fix: fix perms for github token in release workflow

.github/workflows/release.yml
fix release work flow perms to include write access to contents. this allows the github token to push tags to github
=> fix: fix release work flow perms to include write access to contents

package.json, yarn.lock
The change bumps dependency to @amplitude/ua-parser-js@0.7.31.
=> fix: upgrade to @amplitude/ua-parser-js@0.7.31

scripts/deploy_s3.py
Fix s3 script to use **default** aws config associated with an iam role. Access key and secret access key are no longer available to use. We use `aws-actions/configure-aws-credentials@v1` to auth with an iam role. Github actions will assume `github-actions-role` and perform api actions the role has been granted to.
=> fix: fix s3 upload script to use iam role

src/amplitude-client.js, src/options.js, test/amplitude-client.js
- add partner_id support
* Does your PR have a breaking change?:  no
=> feat: add partner_id support

src/amplitude-client.js, src/constants.js
https://discourse.amplitude.com/t/incorrectly-logged-referrer-due-to-cookie-control/7164
This pr for providing the ability to let customers overwrite the referrer info.
The use case:
Customer need to defer the initialization with the cookie control. Before accepting cookies, the users might redirect to other pages. And the `document.referrer` will be set to the last page they were on. So they will lose the original referrer info after enabling tracking.
This pr enable customer using this SDK to pass an overwrite value through url parameter in order to overwrite the referrer info.
=> feat: enable the ability to overwrite the referrer

src/amplitude-client.js, src/options.js, test/amplitude-client.js
- feat: add ingestion_metadata field
Add this option in the configuration, which can be used in the library wrapper/code generation/dynamic loading cases, for setting the `ingestion_metadata` information.
=> feat: add ingestion_metadata field

src/amplitude-client.js
Creates clone of nested objects in `DEFAULT_OPTIONS` to break sharing of references to these nested objects
```
const a = amplitude.getInstance('a')
> undefined
const a = amplitude.getInstance('a')
> undefined
a.options.plan === b.options.plan
> false
a.options.library === b.options.library
> false
a.options.headers === b.options.headers
> false
a.options.ingestionMetadata === b.options.ingestionMetadata
> false
```
=> fix: nested object in options are shared across multiple instances

package.json, yarn.lock
Bumps version for `analytics-connector`. Old version was emitting [[Amplitude] TypeError: Cannot read properties of null (reading ‘length’)](https://discourse.amplitude.com/t/javascript-sdk-amplitude-typeerror-cannot-read-properties-of-null-reading-length/9058) log when setting user id to empty string or null 
=> fix: bump analytics-connector

src/amplitude-client.js
- fix: remove events when 200, no need to check response
User might use the SDK to send events to their proxy server, we should only rely on the 200 status code, not the response content for removing successfully sent events. Otherwise, the same event might get sent to the ingestion host again and again.
=> fix: remove events when 200, no need to check response

.github/workflows/deploy-docs.yml, .github/workflows/lint.yml, .github/workflows/publish-github-packages.yml, .github/workflows/release.yml, .github/workflows/test.yml
- build: upgrade node version
Release dry-run failed due to unsupported node version: https://github.com/amplitude/Amplitude-JavaScript/actions/runs/3944632584/jobs/6750753791. Trying to upgrade the node version to 16.x
=> build: upgrade node version

src/amplitude-client.js, src/cookiestorage.js, test/amplitude-client.js
Delay creation of cookie storage to `init()` to honor `disableCookies` option to prevent creation of test cookie
=> fix: wait to create cookie storage based on user options in init()

src/amplitude-client.js, src/constants.js, test/amplitude-client.js
`unsetParamsReferrerOnNewSession` should also reset `referring_domain` by [definition](https://www.docs.developers.amplitude.com/data/sdks/javascript/#track-referrers). 
=> fix: reset referring_domain
