package.json

The current main path is unresolvable when installed via NPM.

Fixes NPM install via github

---

src/options.js
test/amplitude-client.js
test/amplitude.js

This will be followed by a major version bump.

Default forceHtttps to true

---

src/amplitude-client.js

timesatmp -> timestamp in logEventWithTimestamp jsdoc

Fix amplitude-client jsdoc typo

---

README.md
src/amplitude-client.js
src/amplitude-snippet.js

I previously bumped the version, but forgot to run `make release`.

Run make release on changed files

---

src/amplitude-client.js

feat: add default versionName to react-native

---

src/base-cookie.js

`Constants.COOKIE_TEST` does not exist, should be `Constants.COOKIE_TEST_PREFIX`.

Fix incorrect constant

---

.github/pull_request_template.md
.github/workflows/semantic-pr.yml
README.md

- Fixed `semantic-pr.yml` syntax problems noticed when implementing release workflow on Amplitude-iOS
- Fix dead link in PR template
- Fixed readme grammar
* Does your PR have a breaking change?:  NO

ci: semantic pr fixes

---

src/amplitude-client.js

- Adds warning for users trying to use amplitude-js in a non-browser env

refactor: add non-browser env warning

---

.github/workflows/deploy_docs.yml

Adds `workflows/deploy_docs.yml` to help automate reference website publishing.

ci: github pages deployment

---

Makefile
package.json
yarn.lock

Improves dev UX by rebuilding when there is a file change

build: add watch script

---

.eslintrc.json
package.json
yarn.lock

Prevents accidental disabling of tests

ci: exclusive test linter rule

---

.github/workflows/jira-issue-create.yml

Updates jira issue creation configs

ci: Update jira config

---

.github/workflows/jira-issue-create.yml

Update jira issue create bot
* Does your PR have a breaking change?:  no

chore: Update jira issue create bot

---

src/amplitude-client.js

docs: Add docs for resetSessionid

---

scripts/readme.js
scripts/release.js
scripts/version.js

Readds accidentally removed scripts from #447 

build: fix release scripts

---

README.md

Updates the `CHANGELOG.md` linked in the README to the `main` branch. 

docs: Update CHANGELOG link to main branch

---

.npmignore

Makes `amplitude-snippet.min.js` public in our NPM distribution. Used so that we can embed latest version of snippet into our dev docs

feat: make snippet public in NPM

---

website/generate-jsdoc.js

Swap order of the "Description" and "Default" headers in the Options docs.
Snippet from [the current docs version](https://amplitude.github.io/Amplitude-JavaScript/Options/):

docs(options): fix table headers

---

package.json
yarn.lock

* Does your PR have a breaking change?:   no

fix: update analytics-connector to 1.4.1

---

README.md

Preview: https://github.com/amplitude/Amplitude-JavaScript/tree/AMP-XXXXX-new-sdk#announcement-

chore: announce new sdk on readme

---

.github/workflows/release.yml

build: fix authorize job

---

package.json
yarn.lock

fix: update analytics connector 1.4.2

---

package.json
yarn.lock

update analytics connector to support ie11
* Does your PR have a breaking change?:   no

fix: polyfill object entries for ie11

---

README.md

docs: removes beta tag in announcement of new browser sdk

---

.github/workflows/deploy-docs.yml

Fixes permissions check for docs deploy workflow

build: fixes permissions check for deploy workflow

---

package.json
yarn.lock

Upgrades  @amplitude/utils to latest
Fixes https://github.com/amplitude/Amplitude-TypeScript/issues/206

fix: upgrade @amplitude/utils version

---

package.json
yarn.lock

* Does your PR have a breaking change?:   YES

fix: update analytics connector for bugfix

---

package.json
yarn.lock

fix: upgrade to @amplitude/ua-parser-js@0.7.33

---

src/base64Id.js
src/uuid.js
test/base64Id.js
test/uuid.js

https://amplitude.atlassian.net/browse/AMP-76984
Replace `Math.random` with `crypto.getRandomValues` to avoid uuid collisions
Testing:
- Run `npm test` and pass
- manually run the function and the result follows the uuid format required 

fix: uuid collisions

---

.github/workflows/jira-issue-create.yml

- update issues workflow for AMP project

chore: update issues workflow for AMP project
